In [107]:
print('vishal megamart guard prep')

vishal megamart guard prep


In [108]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df=pd.read_csv('Dataset.csv')
df.head()

school sex address famsize Pstatus  Medu  Fedu     Mjob      Fjob  reason  \
0     GP   F       U     GT3       A     4   4.0  at_home   teacher  course   
1     GP   F       U     GT3       T     1   1.0  at_home     other  course   
2     GP   F       U     LE3       T     1   1.0  at_home     other   other   
3     GP   F       U     GT3       T     4   2.0   health  services    home   
4     GP   F       U     GT3       T     3   3.0    other     other    home   

   ... Dalc  health  absences  G1    G2  G3 Feature_1 Feature_2 Feature_3  \
0  ...    1       3       4.0   0  11.0  11      18.0       2.0       1.0   
1  ...    1       3       2.0   9  11.0  11      17.0       2.0       1.0   
2  ...    2       3       6.0  12  13.0  12      15.0       NaN       3.0   
3  ...    1       5       0.0  14  14.0  14      15.0       3.0       1.0   
4  ...    1       5       0.0  11  13.0  13      16.0       NaN       2.0   

  romantic  
0       no  
1       no  
2       no  
3      yes  
4       no  

[5 rows x 33 columns]

Data cleaning and Encoding

Encoding 

In [109]:
df.select_dtypes(include='object').columns

Index(['school', 'sex', 'address', 'famsize', 'Pstatus', 'Mjob', 'Fjob',
       'reason', 'guardian', 'schoolsup', 'famsup', 'paid', 'activities',
       'nursery', 'higher', 'internet', 'romantic'],
      dtype='object')

In [110]:
n = 120
mx = 0
while (n!=0):
    arr = np.random.permutation(5)
    codes = {'teacher':arr[0],'health':arr[1],'services':arr[2],'at_home':arr[3],'other':arr[4]}
    df['codes'] = df['Mjob'].map(codes)
    corr = ( df['Medu'].corr( df['codes']))
    if(corr>mx):
        mx = corr
        print(arr,corr) 
    n=n-1

[4 0 3 1 2] 0.32777496318862354
[2 3 4 1 0] 0.3493518484148982
[3 4 1 0 2] 0.46300707668771063
[4 2 3 0 1] 0.5699226580421886


In [111]:
n = 120
mx = 0
while (n!=0):
    arr = np.random.permutation(5)
    codes = {'teacher':arr[0],'health':arr[1],'services':arr[2],'at_home':arr[3],'other':arr[4]}
    df['codes'] = df['Fjob'].map(codes)
    corr = ( df['Fedu'].corr( df['codes']))
    if(corr>mx):
        mx = corr
        print(arr,corr) 
    n=n-1

[3 0 4 2 1] 0.0838335287831774
[2 4 1 3 0] 0.24685619916616763
[4 3 2 1 0] 0.3588588106399968
[3 4 2 0 1] 0.38872217918214985


In [112]:
df['famsize']=df['famsize'].replace({'GT3': 1, 'LE3': 0})
df['Mjob']=df['Mjob'].replace({'teacher': 4, 'health': 3, 'services': 2, 'at_home': 0, 'other': 1})
df['Fjob']=df['Fjob'].replace({'teacher': 4, 'health': 3, 'services': 2, 'at_home': 0, 'other': 1})
df['reason']=df['reason'].replace({'home': 0, 'reputation': 1, 'course': 2, 'other': 3})
df['guardian']=df['guardian'].replace({'mother': 1, 'father': 2, 'other': 0})


C:\Users\madha\AppData\Local\Temp\ipykernel_25340\798503812.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['famsize']=df['famsize'].replace({'GT3': 1, 'LE3': 0})
C:\Users\madha\AppData\Local\Temp\ipykernel_25340\798503812.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Mjob']=df['Mjob'].replace({'teacher': 4, 'health': 3, 'services': 2, 'at_home': 0, 'other': 1})
C:\Users\madha\AppData\Local\Temp\ipykernel_25340\798503812.py:3: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a 

In [113]:
from sklearn.preprocessing import LabelEncoder

# Step 1: Drop rows with missing values


# Step 2: Initialize LabelEncoder
le = LabelEncoder()

# Step 3: Loop through object-type columns and encode
for col in df.columns:
    if df[col].dtype == 'object':
        df[col] = le.fit_transform(df[col])

# Now all object columns are encoded as integers
print(df.dtypes)

school          int64
sex             int64
address         int64
famsize       float64
Pstatus         int64
Medu            int64
Fedu          float64
Mjob            int64
Fjob            int64
reason          int64
guardian        int64
traveltime    float64
failures        int64
schoolsup       int64
famsup          int64
paid            int64
activities      int64
nursery         int64
higher          int64
internet        int64
famrel          int64
freetime      float64
goout           int64
Dalc            int64
health          int64
absences      float64
G1              int64
G2            float64
G3              int64
Feature_1     float64
Feature_2     float64
Feature_3     float64
romantic        int64
codes           int32
dtype: object


In [114]:
for col in df.columns:
    if df[col].isna().any():
        print(col, df[col].isna().sum())
      

famsize 50
Fedu 73
traveltime 73
freetime 45
absences 69
G2 35
Feature_1 38
Feature_2 46
Feature_3 39


In [115]:
df_dropped = df.dropna().copy()

In [116]:
df['Fedu'].value_counts(normalize=True)

Fedu
2.0    0.315972
1.0    0.276042
4.0    0.203125
3.0    0.194444
0.0    0.010417
Name: proportion, dtype: float64

In [117]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import cross_val_score
from sklearn.preprocessing import StandardScaler

# Step 1: Drop rows with NaNs in the target
df_clean = df_dropped.dropna(subset=['famsize'])

# Step 2: Drop any features (columns) with NaNs
df_clean = df_clean.dropna(axis=1)

# Step 3: Compute absolute correlations with the binary target
correlations = df_clean.corr().abs()['famsize'].sort_values(ascending=False)

# Step 4: Select top 5 features most correlated with 'higher', excluding 'higher' itself
top_5_features = correlations.drop('famsize').head(5).index.tolist()
print("Top 5 features by correlation:", top_5_features)

# Step 5: Define features and target
X = df_clean[top_5_features]
y = df_clean['famsize']  # already mapped to 0/1

# Step 6: Scale features
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Step 7: Train Logistic Regression with cross-validation
model = LogisticRegression(max_iter=1000)
scores = cross_val_score(model, X_scaled, y, cv=5, scoring='accuracy')

# Step 8: Output results
print("Cross-validation accuracy scores:", scores)
print("Mean accuracy:", scores.mean())

print("Mean cross-validation accuracy:", scores.mean())

Top 5 features by correlation: ['Pstatus', 'Dalc', 'sex', 'Mjob', 'higher']
Cross-validation accuracy scores: [0.75409836 0.63333333 0.76666667 0.68333333 0.73333333]
Mean accuracy: 0.7141530054644809
Mean cross-validation accuracy: 0.7141530054644809


In [118]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import cross_val_score
from sklearn.preprocessing import StandardScaler

# Step 1: Drop rows with NaNs in the target
df_clean = df_dropped.dropna(subset=['Fedu'])

# Step 2: Drop any features (columns) with NaNs
df_clean = df_clean.dropna(axis=1)

# Step 3: Compute absolute correlations with the binary target
correlations = df_clean.corr().abs()['Fedu'].sort_values(ascending=False)

# Step 4: Select top 5 features most correlated with 'higher', excluding 'higher' itself
top_5_features = correlations.drop('Fedu').head(6).index.tolist()
print("Top 5 features by correlation:", top_5_features)

# Step 5: Define features and target
X = df_clean[top_5_features]
y = df_clean['Fedu']  # already mapped to 0/1

# Step 6: Scale features
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Step 7: Train Logistic Regression with cross-validation
model = LogisticRegression(max_iter=1000)
scores = cross_val_score(model, X_scaled, y, cv=6, scoring='accuracy')

# Step 8: Output results
print("Cross-validation accuracy scores:", scores)
print("Mean accuracy:", scores.mean())


Top 5 features by correlation: ['Medu', 'Fjob', 'Mjob', 'traveltime', 'internet', 'school']
Cross-validation accuracy scores: [0.58823529 0.48       0.5        0.38       0.46       0.44      ]
Mean accuracy: 0.47470588235294114


In [119]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import cross_val_score
from sklearn.preprocessing import StandardScaler

# Step 1: Drop rows with NaNs in the target
df_clean = df_dropped.dropna(subset=['traveltime'])

# Step 2: Drop any features (columns) with NaNs
df_clean = df_clean.dropna(axis=1)

# Step 3: Compute absolute correlations with the binary target
correlations = df_clean.corr().abs()['traveltime'].sort_values(ascending=False)

# Step 4: Select top 5 features most correlated with 'higher', excluding 'higher' itself
top_5_features = correlations.drop('traveltime').head(7).index.tolist()
print("Top 5 features by correlation:", top_5_features)

# Step 5: Define features and target
X = df_clean[top_5_features]
y = df_clean['traveltime']  # already mapped to 0/1

# Step 6: Scale features
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Step 7: Train Logistic Regression with cross-validation
model = LogisticRegression(max_iter=1000)
scores = cross_val_score(model, X_scaled, y, cv=7, scoring='accuracy')

# Step 8: Output results
print("Cross-validation accuracy scores:", scores)
print("Mean accuracy:", scores.mean())


Top 5 features by correlation: ['address', 'Medu', 'Fedu', 'school', 'reason', 'internet', 'Mjob']
Cross-validation accuracy scores: [0.58139535 0.60465116 0.62790698 0.62790698 0.72093023 0.58139535
 0.46511628]
Mean accuracy: 0.6013289036544851


In [120]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import cross_val_score
from sklearn.preprocessing import StandardScaler

# Step 1: Drop rows with NaNs in the target
df_clean = df_dropped.dropna(subset=['higher'])

# Step 2: Drop any features (columns) with NaNs
df_clean = df_clean.dropna(axis=1)

# Step 3: Compute absolute correlations with the binary target
correlations = df_clean.corr().abs()['higher'].sort_values(ascending=False)

# Step 4: Select top 5 features most correlated with 'higher', excluding 'higher' itself
top_5_features = correlations.drop('higher').head(5).index.tolist()
print("Top 5 features by correlation:", top_5_features)

# Step 5: Define features and target
X = df_clean[top_5_features]
y = df_clean['higher']  # already mapped to 0/1

# Step 6: Scale features
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Step 7: Train Logistic Regression with cross-validation
model = LogisticRegression(max_iter=1000)
scores = cross_val_score(model, X_scaled, y, cv=5, scoring='accuracy')

# Step 8: Output results
print("Cross-validation accuracy scores:", scores)
print("Mean accuracy:", scores.mean())


Top 5 features by correlation: ['G1', 'G2', 'absences', 'famrel', 'G3']
Cross-validation accuracy scores: [0.75409836 0.78333333 0.8        0.76666667 0.7       ]
Mean accuracy: 0.7608196721311475


In [121]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import cross_val_score
from sklearn.preprocessing import StandardScaler

# Step 1: Drop rows with NaNs in the target
df_clean = df_dropped.dropna(subset=['freetime'])

# Step 2: Drop any features (columns) with NaNs
df_clean = df_clean.dropna(axis=1)

# Step 3: Compute absolute correlations with the binary target
correlations = df_clean.corr().abs()['freetime'].sort_values(ascending=False)

# Step 4: Select top 5 features most correlated with 'higher', excluding 'higher' itself
top_5_features = correlations.drop('freetime').head(5).index.tolist()
print("Top 5 features by correlation:", top_5_features)

# Step 5: Define features and target
X = df_clean[top_5_features]
y = df_clean['freetime']  # already mapped to 0/1

# Step 6: Scale features
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Step 7: Train Logistic Regression with cross-validation
model = LogisticRegression(max_iter=1000)
scores = cross_val_score(model, X_scaled, y, cv=5, scoring='accuracy')

# Step 8: Output results
print("Cross-validation accuracy scores:", scores)
print("Mean accuracy:", scores.mean())


Top 5 features by correlation: ['goout', 'sex', 'famrel', 'paid', 'Feature_3']
Cross-validation accuracy scores: [0.36065574 0.43333333 0.45       0.3        0.43333333]
Mean accuracy: 0.39546448087431696


In [122]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import cross_val_score
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestRegressor
correlations = df_dropped.corr().abs()

# Get top 5 features most correlated with the target (excluding target itself)
top_5_features = correlations['absences'].drop('absences').sort_values(ascending=False).head(5).index.tolist()

# Define features and numerical target
X = df_dropped[top_5_features]
y = df_dropped['absences']

# Scale features
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Regression model
model = RandomForestRegressor()

# Cross-validation with scoring='r2' (or 'neg_mean_squared_error')
scores = cross_val_score(model, X_scaled, y, cv=5, scoring='r2')

print("Cross-validation R² scores:", scores)
print("Mean R² score:", scores.mean())

Cross-validation R² scores: [-0.44721121 -0.0528337  -0.01852673 -0.39573545 -2.87891604]
Mean R² score: -0.7586446276771873


In [123]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import cross_val_score
from sklearn.preprocessing import StandardScaler

# Step 1: Drop rows where the target (G2) is NaN
df_clean = df.dropna(subset=['G2'])

# Step 2: Drop columns (features) that contain any NaN values
df_clean = df_clean.dropna(axis=1)

# Step 3: Compute absolute correlations with target 'G2'
correlations = df_clean.corr().abs()

# Step 4: Get top 5 features most correlated with 'G2', excluding 'G2' itself
top_5_features = (
    correlations['G2']
    .drop('G2')
    .sort_values(ascending=False)
    .head(5)
    .index
    .tolist()
)

# Step 5: Define features and target
X = df_clean[top_5_features]
y = df_clean['G2']

# Step 6: Scale features
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Step 7: Train Linear Regression with cross-validation
model = LinearRegression()
scores = cross_val_score(model, X_scaled, y, cv=5, scoring='r2')

# Output results
print("Top 5 features:", top_5_features)
print("Cross-validation R² scores:", scores)
print("Mean R² score:", scores.mean())


Top 5 features: ['G3', 'G1', 'failures', 'Medu', 'school']
Cross-validation R² scores: [0.81953223 0.8321389  0.90790962 0.87036853 0.84560566]
Mean R² score: 0.8551109878766395


In [130]:
df['Feature_1'].value_counts()
df['Feature_2'].value_counts()  
df['Feature_2'].value_counts(normalize=True) 

Feature_2
2.0    0.462687
1.0    0.338308
3.0    0.145937
4.0    0.053068
Name: proportion, dtype: float64

In [125]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import cross_val_score
from sklearn.preprocessing import StandardScaler

# Step 1: Drop rows with NaNs in the target
df_clean = df_dropped.dropna(subset=['Feature_3'])

# Step 2: Drop any features (columns) with NaNs
df_clean = df_clean.dropna(axis=1)

# Step 3: Compute absolute correlations with the binary target
correlations = df_clean.corr().abs()['Feature_3'].sort_values(ascending=False)

# Step 4: Select top 5 features most correlated with 'higher', excluding 'higher' itself
top_5_features = correlations.drop('Feature_3').head(5).index.tolist()
print("Top 5 features by correlation:", top_5_features)

# Step 5: Define features and target
X = df_clean[top_5_features]
y = df_clean['Feature_3']  # already mapped to 0/1

# Step 6: Scale features
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Step 7: Train Logistic Regression with cross-validation
model = LogisticRegression(max_iter=1000)
scores = cross_val_score(model, X_scaled, y, cv=5, scoring='accuracy')

# Step 8: Output results
print("Cross-validation accuracy scores:", scores)
print("Mean accuracy:", scores.mean())


Top 5 features by correlation: ['Dalc', 'goout', 'sex', 'Feature_2', 'codes']
Cross-validation accuracy scores: [0.45901639 0.45       0.48333333 0.51666667 0.48333333]
Mean accuracy: 0.47846994535519133


In [126]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import cross_val_score
from sklearn.preprocessing import StandardScaler

# Step 1: Drop rows with NaNs in the target
df_clean = df_dropped.dropna(subset=['Feature_2'])

# Step 2: Drop any features (columns) with NaNs
df_clean = df_clean.dropna(axis=1)

# Step 3: Compute absolute correlations with the binary target
correlations = df_clean.corr().abs()['Feature_2'].sort_values(ascending=False)

# Step 4: Select top 5 features most correlated with 'higher', excluding 'higher' itself
top_5_features = correlations.drop('Feature_2').head(5).index.tolist()
print("Top 5 features by correlation:", top_5_features)

# Step 5: Define features and target
X = df_clean[top_5_features]
y = df_clean['Feature_2']  # already mapped to 0/1

# Step 6: Scale features
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Step 7: Train Logistic Regression with cross-validation
model = LogisticRegression(max_iter=1000)
scores = cross_val_score(model, X_scaled, y, cv=5, scoring='accuracy')

# Step 8: Output results
print("Cross-validation accuracy scores:", scores)
print("Mean accuracy:", scores.mean())


Top 5 features by correlation: ['G1', 'G2', 'Feature_3', 'G3', 'sex']
Cross-validation accuracy scores: [0.49180328 0.41666667 0.51666667 0.43333333 0.55      ]
Mean accuracy: 0.4816939890710382


In [127]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, classification_report

# === Step 1: Copy dataframe to avoid modifying original ===
df_model = df.copy()

# === Step 2: Impute Feature_1 with value distribution ===
value_probs = {
    17.0: 0.278232,
    16.0: 0.276596,
    18.0: 0.212766,
    15.0: 0.168576,
    19.0: 0.049100,
    20.0: 0.009820,
    21.0: 0.003273,
    22.0: 0.001637
}
values = list(value_probs.keys())
probs = list(value_probs.values())

# Add missing indicator column
df_model['Feature_1_missing'] = df_model['Feature_1'].isna().astype(int)

# Impute missing values
num_missing = df_model['Feature_1'].isna().sum()
df_model.loc[df_model['Feature_1'].isna(), 'Feature_1'] = np.random.choice(values, size=num_missing, p=probs)

# === Step 3: Optional — Bin the Feature_1 (can improve linear model performance) ===
df_model['Feature_1_binned'] = pd.cut(df_model['Feature_1'], bins=[14, 16, 18, 20, 22], labels=False)

# === Step 4: Prepare features and target ===
# You can use the binned version, original version, and missing indicator
feature_columns = ['Feature_1_binned', 'Feature_1_missing']  # add more good features here
target_column = 'higher'  # assuming already 0/1

X = df_model[feature_columns]
y = df_model[target_column]

# === Step 5: Train-test split ===
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

# === Step 6: Scale features ===
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# === Step 7: Train logistic regression ===
model = LogisticRegression(max_iter=1000)
model.fit(X_train_scaled, y_train)

# === Step 8: Evaluate ===
y_pred = model.predict(X_test_scaled)
accuracy = accuracy_score(y_test, y_pred)

print("Test accuracy:", accuracy)
print("Classification report:")
print(classification_report(y_test, y_pred))


Test accuracy: 0.7846153846153846
Classification report:
              precision    recall  f1-score   support

           0       0.00      0.00      0.00        13
           1       0.78      1.00      0.88       102
           2       0.00      0.00      0.00        15

    accuracy                           0.78       130
   macro avg       0.26      0.33      0.29       130
weighted avg       0.62      0.78      0.69       130



C:\Users\madha\AppData\Roaming\Python\Python313\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\madha\AppData\Roaming\Python\Python313\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\madha\AppData\Roaming\Python\Python313\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} i

In [ ]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression, LinearRegression
from sklearn.preprocessing import StandardScaler

# Helper function: impute a column using predictive model
def predictive_impute(df, target_col, model_type='logistic', round_output=False):
    df_copy = df.copy()
    
    # Get top 5 most correlated features (no NaNs) with target_col
    correlations = df_copy.corr(numeric_only=True)[target_col].drop(target_col).abs()
    non_nan_features = df_copy.columns[df_copy.notna().all()].tolist()
    top_5_features = correlations[correlations.index.isin(non_nan_features)].sort_values(ascending=False).head(5).index.tolist()

    print(f"\n▶ Imputing '{target_col}' using top 5 features: {top_5_features}")
    
    # Split into known and unknown
    known = df_copy[df_copy[target_col].notna()]
    unknown = df_copy[df_copy[target_col].isna()]
    
    if unknown.empty:
        print(f"✅ No missing values in '{target_col}'")
        return df_copy
    
    X_known = known[top_5_features]
    y_known = known[target_col]
    
    X_unknown = unknown[top_5_features]
    
    # Scale features
    scaler = StandardScaler()
    X_known_scaled = scaler.fit_transform(X_known)
    X_unknown_scaled = scaler.transform(X_unknown)
    
    # Choose model type
    if model_type == 'logistic':
        model = LogisticRegression(max_iter=1000)
    elif model_type == 'linear':
        model = LinearRegression()
    else:
        raise ValueError("model_type must be 'logistic' or 'linear'")
    
    model.fit(X_known_scaled, y_known)
    predictions = model.predict(X_unknown_scaled)
    
    if round_output:
        predictions = np.round(predictions).astype(int)
    
    # Impute back into original DataFrame
    df.loc[df[target_col].isna(), target_col] = predictions
    print(f"✅ Imputed {len(predictions)} missing values in '{target_col}'")
    return df

# --- MAIN EXECUTION ---

# Start with your actual DataFrame
# Make sure columns are already encoded
# Assumes df is defined and contains the mentioned columns
df = predictive_impute(df, 'famsize', model_type='logistic')
df = predictive_impute(df, 'traveltime', model_type='logistic')
df= predictive_impute(df, 'Fedu', model_type='logistic')
df = predictive_impute(df, 'Feature_3', model_type='logistic')
df = predictive_impute(df, 'G2', model_type='linear', round_output=True)

# Final check
print("\n🔍 Missing values after imputation:")
print(df[['famsize', 'traveltime', 'G2']].isna().sum())





▶ Imputing 'famsize' using top 5 features: ['Pstatus', 'nursery', 'sex', 'Fjob', 'address']
✅ No missing values in 'famsize'

▶ Imputing 'traveltime' using top 5 features: ['address', 'Medu', 'school', 'Mjob', 'G1']
✅ No missing values in 'traveltime'

▶ Imputing 'Fedu' using top 5 features: ['Medu', 'Fjob', 'Mjob', 'G2', 'G3']
✅ Imputed 73 missing values in 'Fedu'

▶ Imputing 'Feature_3' using top 5 features: ['Dalc', 'goout', 'sex', 'G3', 'G2']
✅ Imputed 39 missing values in 'Feature_3'

▶ Imputing 'G2' using top 5 features: ['G3', 'G1', 'failures', 'school', 'Medu']
✅ No missing values in 'G2'

🔍 Missing values after imputation:
famsize       0
traveltime    0
G2            0
dtype: int64


In [138]:
# Function to impute a column with its mode
def mode_impute(df, column):
    mode_val = df[column].mode()[0]
    num_missing = df[column].isna().sum()
    df[column].fillna(mode_val, inplace=True)
    print(f"✅ Imputed {num_missing} missing values in '{column}' with mode: {mode_val}")

# Apply mode imputation to the specified columns
for col in ['Feature_2', 'Feature_1', 'absences','freetime']:
    mode_impute(df, col)

# Final check
print("\n🔍 Missing values remaining:")
print(df[['Feature_2', 'Feature_1', 'absences','freetime']].isna().sum())


✅ Imputed 0 missing values in 'Feature_2' with mode: 2.0
✅ Imputed 0 missing values in 'Feature_1' with mode: 17.0
✅ Imputed 0 missing values in 'absences' with mode: 0.0
✅ Imputed 45 missing values in 'freetime' with mode: 3.0

🔍 Missing values remaining:
Feature_2    0
Feature_1    0
absences     0
freetime     0
dtype: int64


C:\Users\madha\AppData\Local\Temp\ipykernel_25340\3020811919.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[column].fillna(mode_val, inplace=True)


In [139]:
cols_with_na = df.columns[df.isna().any()].tolist()
print("Columns with missing values:", cols_with_na)

Columns with missing values: []
